import {build} from 'esbuild';import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
class Store{rows=new Map();async getWithMetadata(k){return this.rows.has(k)?structuredClone(this.rows.get(k)):null}async setJSON(k,data,o={}){const row=this.rows.get(k);if(o.onlyIfNew&&row||o.onlyIfMatch&&o.onlyIfMatch!==row?.etag)return {modified:false};this.rows.set(k,{data:structuredClone(data),etag:crypto.randomUUID(),metadata:{}});return {modified:true}}async set(k,data,o){this.rows.set(k,{data,metadata:o.metadata,etag:crypto.randomUUID()})}}
globalThis.stores=new Map();globalThis.getTestStore=(p,o)=>{const key=p+o.name;if(!stores.has(key))stores.set(key,new Store());return stores.get(key)};
const mock={name:'mock-blobs',setup(b){b.onResolve({filter:/^@netlify\/blobs$/},()=>({path:'mock',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:"export const getStore=o=>globalThis.getTestStore('prod:',o);export const getDeployStore=o=>globalThis.getTestStore('preview:',o)"}))}};
await build({entryPoints:['netlify/functions/_shared/ai.mts','netlify/functions/ai-worker-background.mts','netlify/functions/_shared/project.mts','netlify/functions/_shared/image-requests.mts'],outdir:'.test-build/ai',outbase:'netlify/functions',bundle:true,platform:'node',format:'esm',outExtension:{'.js':'.mjs'},plugins:[mock]});
const ai=await import('../../.test-build/ai/_shared/ai.mjs'),{initial}=await import('../../.test-build/ai/_shared/project.mjs'),{default:worker}=await import('../../.test-build/ai/ai-worker-background.mjs');
const images=await import('../../.test-build/ai/_shared/image-requests.mjs');
let env;
beforeEach(()=>{stores.clear();env={CONTEXT:'production',URL:'https://site.example',DEPLOY_URL:'https://deploy.example',OPENAI_API_KEY:'test-only-key',OPENAI_BASE_URL:'https://provider.example/v1'};globalThis.Netlify={env:{get:k=>env[k]}}});
const result=()=>({summary:'관찰 초안',photos:[{source:'/uploads/photo.jpg',observation:'기둥과 출입구'}],quotes:[{source:'/uploads/quote.pdf',vendor:'시공업체',contact:'미확인',subtotal:10000,vat:1000,total:11000,notes:'원본 확인',items:[{item:'조명',qty:1,unit:'개',price:10000,amount:10000}]}],warnings:['현장 실측 필요']});
const zone=()=>{const z=initial().zones['1'];z.scope='벽면 미장과 LED 조명';z.records=[{kind:'before',url:'/uploads/photo.jpg',viewpoint:'입구'}];z.quotes=[{url:'/uploads/quote.pdf',name:'견적.pdf'}];return z};
async function seed(){const f=ai.fileStore();await f.set('photo.jpg',new Uint8Array([255,216,255,0]).buffer,{metadata:{mime:'image/jpeg'}});await f.set('quote.pdf',new TextEncoder().encode('%PDF-1.7').buffer,{metadata:{mime:'application/pdf'}})}
test('configuration and input prerequisites block provider calls',async()=>{delete env.OPENAI_API_KEY;await assert.rejects(ai.queueAI('1',zone(),'all','https://site.example','owner'),/연결 설정/);env.OPENAI_API_KEY='test';await assert.rejects(ai.queueAI('1',initial().zones['1'],'all','https://site.example','owner'),/먼저 등록/);const z=zone();z.scope='';await assert.rejects(ai.queueAI('1',z,'all','https://site.example','owner'),/공사 내용/)});
test('analysis validates numeric uncertainty and unsafe amounts',()=>{assert.equal(ai.parseAnalysis(JSON.stringify(result())).quotes[0].total,11000);const r=result();r.quotes[0].total=-1;assert.throws(()=>ai.parseAnalysis(JSON.stringify(r)));assert.throws(()=>ai.parseAnalysis('not JSON'))});
test('job details hide dispatch secret and detect stale input',()=>{const z=zone(),job={id:'id',status:'completed',fingerprint:ai.fingerprint(z),secretHash:'secret',snapshot:z};assert.equal(ai.publicJob(job,z).secretHash,undefined);assert.equal(ai.publicJob(job,z).stale,false);z.scope='변경';assert.equal(ai.publicJob(job,z).stale,true);assert.equal(ai.publicJob({...job,status:'running',created:new Date(Date.now()-17*60000).toISOString()},z).status,'failed')});
test('queue uses same deploy, handles duplicate work and secret stays private',async()=>{let dispatch;globalThis.fetch=async(url,o)=>{dispatch={url,body:JSON.parse(o.body)};return new Response(null,{status:202})};const job=await ai.queueAI('1',zone(),'all','https://site.example','owner');assert.equal(dispatch.url,'https://deploy.example/.netlify/functions/ai-worker-background');assert.equal(job.secretHash,undefined);await assert.rejects(ai.queueAI('1',zone(),'all','https://site.example','owner'),/진행 중/)});
test('PDF + image recognition followed by referenced edit saves generated JPEG',async()=>{await seed();const calls=[];globalThis.fetch=async(url,o)=>{calls.push({url,body:o.body});return new Response(JSON.stringify(url.endsWith('/chat/completions')?{choices:[{message:{content:JSON.stringify(result())}}]}:{data:[{b64_json:Buffer.from([255,216,255,0]).toString('base64')}]}))};const generated=await ai.runAI({id:'job',zone:'1',mode:'all',snapshot:zone(),sources:[...zone().records,...zone().quotes]});const request=JSON.parse(calls[0].body);assert(request.messages[1].content.some(c=>c.type==='file'));assert(request.messages[1].content.some(c=>c.type==='image_url'));assert.equal(calls[1].body.get('model'),'gpt-image-1.5');assert.equal(calls[1].body.getAll('image[]').length,1);assert.equal(generated.image.reference,'/uploads/photo.jpg');assert(await ai.fileStore().getWithMetadata('ai-job.jpg'))});
test('worker rejects invalid token and runs exactly once when invoked twice',async()=>{await seed();let paid=0;globalThis.fetch=async()=>{paid++;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(result())}}]}))};const secret='dispatch-secret',job={id:'job',zone:'1',mode:'analyze',status:'queued',snapshot:zone(),sources:[...zone().records,...zone().quotes],secretHash:createHash('sha256').update(secret).digest('hex')};await ai.aiStore().setJSON('1',job);const req=token=>new Request('https://deploy.example/.netlify/functions/ai-worker-background',{method:'POST',body:JSON.stringify({zone:'1',id:'job',secret:token})});await worker(req('wrong'));assert.equal(paid,0);await Promise.all([worker(req(secret)),worker(req(secret))]);assert.equal(paid,1);assert.equal((await ai.aiStore().getWithMetadata('1')).data.status,'completed')});
test('image failure preserves successful recognition in job',async()=>{await seed();globalThis.fetch=async url=>url.endsWith('/chat/completions')?new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(result())}}]})):new Response('{}',{status:429});const secret='key';await ai.aiStore().setJSON('1',{id:'job',zone:'1',mode:'all',status:'queued',snapshot:zone(),sources:[...zone().records,...zone().quotes],secretHash:createHash('sha256').update(secret).digest('hex')});await worker(new Request('https://deploy.example/worker',{method:'POST',body:JSON.stringify({zone:'1',id:'job',secret})}));const stored=(await ai.aiStore().getWithMetadata('1')).data;assert.equal(stored.status,'failed');assert.equal(stored.result.summary,'관찰 초안');assert.match(stored.error,/한도/) });

test('one request per before photo, repeat requests do not regenerate completed images',async()=>{const z=zone();z.records.push({kind:'before',url:'/uploads/photo2.jpg',viewpoint:'안쪽'});const dispatches=[];globalThis.fetch=async(url,o)=>{dispatches.push(JSON.parse(o.body));return new Response(null,{status:202})};const list=await images.createImageRequests('1',z,'owner','https://site.example');assert.equal(list.length,2);assert.equal(dispatches.length,2);assert.notEqual(dispatches[0].requestKey,dispatches[1].requestKey);assert.equal(list[0].recipient,'에테르니언');assert.equal(list[0].secretHash,undefined);await images.createImageRequests('1',z,'owner','https://site.example');assert.equal(dispatches.length,2)});
test('requests are recorded without key/scope and changed plans produce stale markers',async()=>{delete env.OPENAI_API_KEY;const z=zone();const list=await images.createImageRequests('1',z,'owner','https://site.example');assert.equal(list[0].status,'waiting');assert.equal(list[0].stale,false);z.scope='다른 계획';assert.equal((await images.listImageRequests('1',z))[0].stale,true);await assert.rejects(images.createImageRequests('1',z,'owner','https://site.example',['/uploads/forged.jpg']),/사진/)});
test('manual-only requests do not invoke provider even when configured',async()=>{globalThis.fetch=async()=>{throw Error('must not dispatch')};const list=await images.createImageRequests('1',zone(),'owner','https://site.example',undefined,false);assert.equal(list[0].status,'waiting');assert.match(list[0].error,/관리자/)});
test('image worker stores output under photo-specific request key',async()=>{await seed();const z=zone();let body;globalThis.fetch=async(url,o)=>{body=JSON.parse(o.body);return new Response(null,{status:202})};const list=await images.createImageRequests('1',z,'owner','https://site.example');globalThis.fetch=async url=>new Response(JSON.stringify(url.endsWith('/chat/completions')?{choices:[{message:{content:JSON.stringify({...result(),quotes:[]})}}]}:{data:[{b64_json:Buffer.from([255,216,255,0]).toString('base64')}]}));await worker(new Request('https://deploy.example/worker',{method:'POST',body:JSON.stringify(body)}));const done=(await images.listImageRequests('1',z))[0];assert.equal(done.status,'completed');assert.equal(done.image.reference,'/uploads/photo.jpg');assert.equal(done.key,list[0].key)});
test('comparison selection rejects unrelated and duplicate quote files',async()=>{await assert.rejects(ai.queueAI('1',zone(),'compare','https://site.example','owner',['/uploads/forged.pdf']),/대상/);await assert.rejects(ai.queueAI('1',zone(),'compare','https://site.example','owner',['/uploads/quote.pdf']),/2건/)});

test('multiple quote recognition reaches comparison with original numeric values',async()=>{await seed();await ai.fileStore().set('quote2.pdf',new TextEncoder().encode('%PDF-1.7').buffer,{metadata:{mime:'application/pdf'}});const z=zone();z.records=[];z.quotes.push({url:'/uploads/quote2.pdf',name:'업체2.pdf'});const extracted=result();extracted.photos=[];extracted.quotes.push({...structuredClone(extracted.quotes[0]),source:'/uploads/quote2.pdf',vendor:'두번째 업체',total:22000,subtotal:20000,vat:2000,items:[{item:'조명',qty:1,unit:'개',price:20000,amount:20000}]});globalThis.fetch=async(url,o)=>{const b=JSON.parse(o.body),name=b.response_format.json_schema.name;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(name==='construction_analysis'?extracted:{summary:'업체별 대조',groups:[{label:'조명',note:'규격 확인',entries:[{source:'/uploads/quote.pdf',itemIndex:0},{source:'/uploads/quote2.pdf',itemIndex:0}]}],reviews:[],warnings:[]})}}]}))};const output=await ai.runAI({id:'compare',zone:'1',mode:'compare',snapshot:z,sources:z.quotes});assert.equal(output.result.comparison.totalSpread,11000);assert.equal(output.result.comparison.rows[0].spread,10000);assert.equal(output.image,null)});
