import {build} from 'esbuild';import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
class Store{rows=new Map();async getWithMetadata(k){const r=this.rows.get(k);return r?structuredClone(r):null}async setJSON(k,data,o={}){const r=this.rows.get(k);if((o.onlyIfNew&&r)||(o.onlyIfMatch&&o.onlyIfMatch!==r?.etag))return {modified:false};this.rows.set(k,{data:structuredClone(data),etag:crypto.randomUUID(),metadata:{}});return {modified:true}}async set(k,data,o){this.rows.set(k,{data,metadata:o.metadata})}async delete(k){this.rows.delete(k)}}
globalThis.testStores=new Map();globalThis.getTestStore=(prefix,o)=>{const key=prefix+o.name;if(!testStores.has(key))testStores.set(key,new Store());return testStores.get(key)};
globalThis.Netlify={env:{get:k=>k==='URL'?'https://arirang.netlify.app':globalThis.testContext}};
await build({entryPoints:['netlify/functions/api.mts'],outfile:'.test-build/api.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'blobs-mock',setup(b){b.onResolve({filter:/^@netlify\/blobs$/},()=>({path:'blobs',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:"export const getStore=o=>globalThis.getTestStore('site:',o);export const getDeployStore=o=>globalThis.getTestStore('deploy:',o);"}))}}]});
const {default:handler}=await import('../../.test-build/api.mjs');
const origin='https://arirang.netlify.app';const request=(path,method='GET',body,auth=true)=>new Request(origin+path,{method,headers:{origin,...(auth?{cookie:'nf_jwt=valid'}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
beforeEach(()=>{testStores.clear();globalThis.testContext='production';globalThis.fetch=async()=>new Response(JSON.stringify({id:'owner',app_metadata:{roles:['admin']}}))});
test('anonymous cannot write or read real files',async()=>{assert.equal((await handler(request('/api/photo/1','POST',{},false))).status,401);assert.equal((await handler(request('/uploads/test.pdf','GET',undefined,false))).status,401);assert.equal((await handler(request('/api/project','GET',undefined,false))).status,200)});
test('unprivileged account denied even with JWT cookie',async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({id:'other',user_metadata:{roles:['admin']},app_metadata:{roles:[]}}));assert.equal((await handler(request('/api/zone/1','PUT',{}))).status,401)});
test('save survives reads and stale edit receives conflict',async()=>{let p=await (await handler(request('/api/project'))).json();p.zones['1'].scope='전등 교체';const b={...p.zones['1'],version:p.version};assert.equal((await handler(request('/api/zone/1','PUT',b))).status,200);assert.equal((await handler(request('/api/zone/1','PUT',b))).status,409);p=await (await handler(request('/api/project'))).json();assert.equal(p.zones['1'].scope,'전등 교체');assert.equal(p.audit[0].actor,'owner')});
test('concurrent saves have exactly one winner via ETag',async()=>{const p=await (await handler(request('/api/project'))).json();const body={...p.zones['1'],version:0};const results=await Promise.all([handler(request('/api/zone/1','PUT',body)),handler(request('/api/zone/1','PUT',body))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409])});
test('preview storage is separated from production',async()=>{const p=await (await handler(request('/api/project'))).json();await handler(request('/api/zone/1','PUT',{...p.zones['1'],scope:'운영 기록',version:0}));globalThis.testContext='deploy-preview';const preview=await (await handler(request('/api/project'))).json();assert.equal(preview.version,0);assert.equal(preview.zones['1'].scope,'')});
test('PDF upload is persistent and zone edit preserves attachment',async()=>{let p=await (await handler(request('/api/project'))).json();p=await (await handler(request('/api/quote/1','POST',{version:p.version,name:'견적.pdf',content:'data:application/pdf;base64,'+Buffer.from('%PDF-1.7').toString('base64')}))).json();const url=p.zones['1'].quotes[0].url;assert.equal((await handler(request(url))).headers.get('Content-Type'),'application/pdf');const updated=await (await handler(request('/api/zone/1','PUT',{...p.zones['1'],version:p.version,quotes:[]}))).json();assert.equal(updated.zones['1'].quotes.length,1)});
test('cross-origin write is denied',async()=>{const req=new Request(origin+'/api/zone/1',{method:'PUT',headers:{cookie:'nf_jwt=valid',origin:'https://other.example'},body:'{}'});assert.equal((await handler(req)).status,403)});
