import {build} from 'esbuild';import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
class Store{rows=new Map();async getWithMetadata(k){const r=this.rows.get(k);return r?structuredClone(r):null}async setJSON(k,data,o={}){const r=this.rows.get(k);if((o.onlyIfNew&&r)||(o.onlyIfMatch&&o.onlyIfMatch!==r?.etag))return {modified:false};this.rows.set(k,{data:structuredClone(data),etag:crypto.randomUUID(),metadata:{}});return {modified:true}}async set(k,data,o){this.rows.set(k,{data,metadata:o.metadata})}async delete(k){this.rows.delete(k)}}
globalThis.testStores=new Map();globalThis.getTestStore=(prefix,o)=>{const key=prefix+o.name;if(!testStores.has(key))testStores.set(key,new Store());return testStores.get(key)};
globalThis.Netlify={env:{get:k=>k==='URL'?'https://arirang.netlify.app':k==='CONTEXT'?globalThis.testContext:undefined}};
await build({entryPoints:['netlify/functions/api.mts'],outfile:'.test-build/api.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'blobs-mock',setup(b){b.onResolve({filter:/^@netlify\/blobs$/},()=>({path:'blobs',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:"export const getStore=o=>globalThis.getTestStore('site:',o);export const getDeployStore=o=>globalThis.getTestStore('deploy:',o);"}))}}]});
const {default:handler}=await import('../../.test-build/api.mjs');
const origin='https://arirang.netlify.app';const request=(path,method='GET',body,auth=true)=>new Request(origin+path,{method,headers:{origin,...(auth?{cookie:'nf_jwt=valid'}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
beforeEach(()=>{testStores.clear();globalThis.testContext='production';globalThis.fetch=async()=>new Response(JSON.stringify({id:'owner',app_metadata:{roles:['admin']}}))});
test('anonymous cannot write or read real files',async()=>{assert.equal((await handler(request('/api/photo/1','POST',{},false))).status,401);assert.equal((await handler(request('/uploads/test.pdf','GET',undefined,false))).status,401);assert.equal((await handler(request('/api/project','GET',undefined,false))).status,200)});
test('unprivileged account denied even with JWT cookie',async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({id:'other',user_metadata:{roles:['admin']},app_metadata:{roles:[]}}));assert.equal((await handler(request('/api/zone/1','PUT',{}))).status,401)});
test('save survives reads and stale edit receives conflict',async()=>{let p=await (await handler(request('/api/project'))).json();p.zones['1'].scope='전등 교체';const b={...p.zones['1'],version:p.version};assert.equal((await handler(request('/api/zone/1','PUT',b))).status,200);assert.equal((await handler(request('/api/zone/1','PUT',b))).status,409);p=await (await handler(request('/api/project'))).json();assert.equal(p.zones['1'].scope,'전등 교체');assert.equal(p.audit[0].actor,'owner')});
test('concurrent saves have exactly one winner via ETag',async()=>{const p=await (await handler(request('/api/project'))).json();const body={...p.zones['1'],version:0};const results=await Promise.all([handler(request('/api/zone/1','PUT',body)),handler(request('/api/zone/1','PUT',body))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409])});
test('preview storage is separated from production',async()=>{const p=await (await handler(request('/api/project'))).json();await handler(request('/api/zone/1','PUT',{...p.zones['1'],scope:'운영 기록',version:0}));globalThis.testContext='deploy-preview';const preview=await (await handler(request('/api/project'))).json();assert.equal(preview.version,0);assert.equal(preview.zones['1'].scope,'')});
test('PDF upload is persistent and zone edit preserves attachment',async()=>{let p=await (await handler(request('/api/project'))).json();p=await (await handler(request('/api/quote/1','POST',{version:p.version,name:'견적.pdf',content:'data:application/pdf;base64,'+Buffer.from('%PDF-1.7').toString('base64')}))).json();const url=p.zones['1'].quotes[0].url;assert.equal((await handler(request(url))).headers.get('Content-Type'),'application/pdf');const updated=await (await handler(request('/api/zone/1','PUT',{...p.zones['1'],version:p.version,quotes:[]}))).json();assert.equal(updated.zones['1'].quotes.length,1)});
test('cross-origin write is denied',async()=>{const req=new Request(origin+'/api/zone/1',{method:'PUT',headers:{cookie:'nf_jwt=valid',origin:'https://other.example'},body:'{}'});assert.equal((await handler(req)).status,403)});

test('AI jobs require admin and configured provider',async()=>{assert.equal((await handler(request('/api/ai/1','POST',{version:0,mode:'all'},false))).status,401);assert.equal((await handler(request('/api/ai/1','POST',{version:0,mode:'all'}))).status,503);assert.equal((await (await handler(request('/api/session'))).json()).aiReady,false)});

test('photo-specific requests and manual returned result remain connected and private',async()=>{const jpeg='data:image/jpeg;base64,'+Buffer.from([255,216,255,0]).toString('base64');const p=await (await handler(request('/api/photo/1','POST',{version:0,image:jpeg,kind:'before',date:'2026-10-06',viewpoint:'입구',note:'공사 전'}))).json();const response=await handler(request('/api/image-requests/1','POST',{version:p.version,process:false}));const list=await response.json();assert.equal(response.status,202);assert.equal(list.length,1);assert.equal(list[0].status,'waiting');assert.equal((await handler(request('/api/image-requests/1','GET',undefined,false))).status,401);const uploaded=await handler(request('/api/image-result/1/'+list[0].key,'POST',{image:jpeg}));const result=await uploaded.json();assert.equal(uploaded.status,200);assert.equal(result[0].image.reference,p.zones['1'].records[0].url);assert.equal(result[0].status,'completed')});


test('public view contains current progress and only active contractor contacts without financial documents',async()=>{
 let p=await (await handler(request('/api/project'))).json();
 p=await (await handler(request('/api/zone/1','PUT',{...p.zones['1'],version:p.version,scope:'private scope',contractors:{전기공사:{name:'진행 업체',contact:'현장 담당',phone:'042-000-0000',status:'진행 중'},인테리어:{name:'견적 업체',contact:'비공개',phone:'secret',status:'예정'}},costs:[{trade:'전기공사',item:'private item',unit:'식',qty:1,price:100000,vat:10,note:'private note'}]}))).json();
 p=await (await handler(request('/api/quote/1','POST',{version:p.version,name:'secret.pdf',content:'data:application/pdf;base64,'+Buffer.from('%PDF-1.7').toString('base64')}))).json();
 const pub=await (await handler(request('/api/project','GET',undefined,false))).json();
 assert.equal(pub.zones['1'].steps[2].status,'진행 중');assert.equal(pub.zones['1'].steps[2].note,'');assert.deepEqual(Object.keys(pub.zones['1'].contractors),['전기공사']);assert.equal(pub.zones['1'].contractors.전기공사.phone,'042-000-0000');assert.deepEqual(pub.zones['1'].quotes,[]);assert.deepEqual(pub.zones['1'].costs,[]);assert.equal(pub.zones['1'].scope,'');assert.deepEqual(pub.audit,[]);assert.equal((await handler(request(p.zones['1'].quotes[0].url,'GET',undefined,false))).status,401);
});
test('contract attachments are admin-only and preserved by zone updates',async()=>{
 const content='data:application/pdf;base64,'+Buffer.from('%PDF-1.7').toString('base64');assert.equal((await handler(request('/api/contract/1','POST',{version:0,name:'contract.pdf',vendor:'업체',content},false))).status,401);
 let p=await (await handler(request('/api/contract/1','POST',{version:0,name:'contract.pdf',vendor:'업체',content}))).json();const url=p.zones['1'].contracts[0].url;
 assert.equal((await handler(request(url))).status,200);assert.equal((await handler(request(url,'GET',undefined,false))).status,401);
 p=await (await handler(request('/api/zone/1','PUT',{...p.zones['1'],contracts:[],version:p.version}))).json();assert.equal(p.zones['1'].contracts.length,1);
 const pub=await (await handler(request('/api/project','GET',undefined,false))).json();assert.equal(JSON.stringify(pub).includes(url),false);
});

test('Kakao TXT diary preserves original bytes and creates escaped-ready web text privately',async()=>{
 const text='2026-10-07 공사일지\n전기공사 배선 작업\n<script>alert(1)</script>',bytes=Buffer.from(text),content='data:text/plain;base64,'+bytes.toString('base64');
 assert.equal((await handler(request('/api/diary/1','POST',{version:0,name:'카톡.txt',content},false))).status,401);
 const response=await handler(request('/api/diary/1','POST',{version:0,name:'카톡.txt',content,date:'2026-10-07'}));assert.equal(response.status,200);const p=await response.json(),d=p.zones['1'].diaries[0];assert.equal(d.status,'completed');assert.equal(d.text,text);assert.equal(d.secretHash,undefined);
 const original=await handler(request(d.url));assert.equal(Buffer.from(await original.arrayBuffer()).equals(bytes),true);assert.equal((await handler(request(d.url,'GET',undefined,false))).status,401);
 const pub=await (await handler(request('/api/project','GET',undefined,false))).json();assert.equal(JSON.stringify(pub).includes(text),false);assert.equal(pub.zones['1'].diaries,undefined);
 const saved=await (await handler(request('/api/zone/1','PUT',{...p.zones['1'],version:p.version,diaries:[]}))).json();assert.equal(saved.zones['1'].diaries.length,1);
});
test('PDF diary remains stored when OCR is unavailable; unauthorized retries and malformed UTF8 are rejected',async()=>{
 const response=await handler(request('/api/diary/1','POST',{version:0,name:'일지.pdf',content:'data:application/pdf;base64,'+Buffer.from('%PDF-1.7').toString('base64')}));const p=await response.json(),d=p.zones['1'].diaries[0];assert.equal(d.status,'waiting');assert.equal((await handler(request(d.url))).status,200);assert.equal((await handler(request('/api/diary-retry/'+d.id,'POST',{},false))).status,401);assert.equal((await handler(request('/api/diary-retry/'+d.id,'POST',{}))).status,503);
 assert.equal((await handler(request('/api/diary/1','POST',{version:p.version,name:'invalid.txt',content:'data:text/plain;base64,/w=='}))).status,400);
});

test('diary review requires admin confirmation, preserves original, and applies only explicitly chosen stage',async()=>{
 const content='data:text/plain;base64,'+Buffer.from('원문 배선 공사').toString('base64');let p=await (await handler(request('/api/diary/1','POST',{version:0,name:'일지.txt',vendor:'전기업체',trade:'전기공사',content}))).json();const d=p.zones['1'].diaries[0],url='/api/diary-review/1/'+d.id;
 const body={version:p.version,text:'관리자 대조: 배선 공사 완료',confirm:true,stepIndex:2,status:'완료',owner:'관리자',note:'원본 일지 및 현장 대조',start:'2026-10-06',end:'2026-10-07'};
 assert.equal((await handler(request(url,'POST',body,false))).status,401);assert.equal((await handler(request(url,'POST',{...body,confirm:false}))).status,400);assert.equal((await handler(request(url,'POST',{...body,owner:''}))).status,400);assert.equal((await handler(request(url.replace('/1/','/3/'),'POST',body))).status,404);
 const response=await handler(request(url,'POST',body));assert.equal(response.status,200);p=await response.json();assert.equal(p.zones['1'].steps[2].status,'완료');assert.equal(p.zones['1'].steps[3].status,'예정');assert.equal(p.zones['1'].diaries[0].text,'원문 배선 공사');assert.equal(p.zones['1'].diaries[0].review.text,body.text);assert.equal(p.zones['1'].diaries[0].review.actor,'owner');assert.equal(p.audit.at(-1).action,'diary-review');assert.equal((await handler(request(url,'POST',body))).status,409);
 assert.equal(await (await handler(request(d.url))).text(),'원문 배선 공사');const pub=await (await handler(request('/api/project','GET',undefined,false))).json();assert.equal(pub.zones['1'].steps[2].status,'완료');assert.equal(pub.zones['1'].diaries,undefined);
});
test('review-only diary confirmation does not change progress and premature handover is blocked',async()=>{
 let p=await (await handler(request('/api/diary/1','POST',{version:0,name:'일지.txt',content:'data:text/plain;base64,'+Buffer.from('작업 기록').toString('base64')}))).json();const before=structuredClone(p.zones['1'].steps),url='/api/diary-review/1/'+p.zones['1'].diaries[0].id;
 p=await (await handler(request(url,'POST',{version:p.version,text:'대조한 작업 기록',confirm:true,stepIndex:null}))).json();assert.deepEqual(p.zones['1'].steps,before);assert.equal(p.zones['1'].diaries[0].review.stepIndex,null);
 assert.equal((await handler(request(url,'POST',{version:p.version,text:'인계',confirm:true,stepIndex:5,status:'완료',owner:'관리자',note:'인계'}))).status,400);
});
