import {build} from 'esbuild';import {test} from 'node:test';import assert from 'node:assert/strict';
await build({entryPoints:['netlify/functions/_shared/quote-comparison.mts'],outfile:'.test-build/comparison.mjs',bundle:true,platform:'node',format:'esm'});
const {compareQuotes,validateMapping}=await import('../../.test-build/comparison.mjs');
const quote=(source,price,qty=2)=>({source,vendor:source,trade:'전기',total:price*qty,subtotal:price*qty,vat:0,items:[{item:'LED 조명',qty,unit:'개',price,amount:price*qty}]});
test('identical quantities compare original amounts and spread',()=>{const c=compareQuotes([quote('a',100),quote('b',200)]);assert.equal(c.rows[0].spread,200);assert.equal(c.totalSpread,200);assert.equal(c.rows[0].offers[1].item.price,200)});
test('quantity differences are flagged without normalized invented amounts',()=>{const c=compareQuotes([quote('a',100,2),quote('b',100,4)]);assert.equal(c.rows[0].comparable,false);assert.equal(c.rows[0].spread,null)});
test('missing item is not assumed excluded or free',()=>{const q=quote('b',100);q.items=[];const c=compareQuotes([quote('a',100),q]);assert.equal(c.rows[0].offers[1].status,'견적에 미기재');assert.equal(c.rows[0].offers[1].item,null)});
test('reject forged source, duplicated item mapping and invalid indexes',()=>{const q=[quote('a',100),quote('b',200)];const mapping={summary:'비교',groups:[{label:'조명',note:'규격 확인',entries:[{source:'a',itemIndex:0}]}],reviews:[],warnings:[]};assert(validateMapping(JSON.stringify(mapping),q));mapping.groups[0].entries.push({source:'other',itemIndex:0});assert.throws(()=>validateMapping(JSON.stringify(mapping),q));mapping.groups[0].entries[1]={source:'a',itemIndex:0};assert.throws(()=>validateMapping(JSON.stringify(mapping),q))});
test('AI omitted original items remain visible; arithmetic mismatch blocks comparability',()=>{const a=quote('a',100),b=quote('b',200);b.items[0].amount=999;const c=compareQuotes([a,b],{summary:'대조',groups:[],reviews:[],warnings:[]});assert.equal(c.rows.length,1);assert.equal(c.rows[0].comparable,false);assert.match(c.rows[0].offers[1].status,/불일치/)});
