import {build} from 'esbuild';import {test} from 'node:test';import assert from 'node:assert/strict';
await build({entryPoints:['netlify/functions/drawings.mts'],outfile:'.test-build/drawings.mjs',bundle:true,platform:'node',format:'esm',packages:'external'});
const {serve}=await import('../../.test-build/drawings.mjs');
const owner={id:'owner',email:'owner@example.com',app_metadata:{roles:['admin']}};
const viewer={id:'v',email:'viewer@example.com',confirmed_at:'2026-01-01',app_metadata:{roles:[]}};
class Store{rows=new Map([['current',{id:'private',pages:9}],['private/original.pdf',new TextEncoder().encode('%PDF-1.7').buffer],['private/page1.jpg',new Uint8Array([255,216,255,1]).buffer]]);async get(k){return this.rows.get(k)||null}async setJSON(k,v){this.rows.set(k,v)}async set(k,v){this.rows.set(k,v)}}
const request=(path,body,origin='https://site.example')=>new Request('https://site.example/drawings-api/'+path,body?{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)}:{});
test('anonymous cannot learn manifest or retrieve private data',async()=>{const store=new Store();for(const path of ['original.pdf','page/1'])assert.equal((await serve(request(path),store,null)).status,401);const session=await(await serve(request('session'),store,null)).json();assert.equal(session.ready,false);assert.equal(session.pages,0)});
test('only server-controlled admin role authorizes PDF',async()=>{const store=new Store();const forged={...viewer,user_metadata:{roles:['admin']}};assert.equal((await serve(request('original.pdf'),store,forged)).status,403);assert.equal((await serve(request('original.pdf'),store,owner)).status,200)});
test('grant permits confirmed viewer images with watermark, denies PDF, revocation immediate',async()=>{const store=new Store();assert.equal((await serve(request('grant',{email:viewer.email,active:true}),store,viewer)).status,403);assert.equal((await serve(request('grant',{email:viewer.email,active:true}),store,owner)).status,200);const image=await serve(request('page/1'),store,viewer);assert.equal(image.status,200);assert.match(await image.text(),/viewer@example.com/);assert.match(image.headers.get('Cache-Control'),/no-store/);assert.equal((await serve(request('original.pdf'),store,viewer)).status,403);assert.equal((await serve(request('page/1'),store,{...viewer,confirmed_at:null})).status,403);await serve(request('grant',{email:viewer.email,active:false}),store,owner);assert.equal((await serve(request('page/1'),store,viewer)).status,403)});
test('cross-origin changes blocked, malformed path blocked, nonadmin import blocked',async()=>{const store=new Store();assert.equal((await serve(request('grant',{email:viewer.email,active:true},'https://evil.example'),store,owner)).status,403);assert.equal((await serve(request('page/%2e%2e%2foriginal.pdf'),store,owner)).status,404);assert.equal((await serve(request('import',{fake:1}),store,viewer)).status,403)});
