import {build} from 'esbuild';import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
class Store{rows=new Map();async getWithMetadata(k){return this.rows.has(k)?structuredClone(this.rows.get(k)):null}async setJSON(k,data,o={}){const r=this.rows.get(k);if(o.onlyIfNew&&r||o.onlyIfMatch&&o.onlyIfMatch!==r?.etag)return {modified:false};this.rows.set(k,{data:structuredClone(data),etag:crypto.randomUUID(),metadata:{}});return {modified:true}}async set(k,data,o){this.rows.set(k,{data,metadata:o.metadata,etag:crypto.randomUUID()})}async delete(k){this.rows.delete(k)}}
globalThis.stores=new Map();globalThis.getTestStore=(p,o)=>{const key=p+o.name;if(!stores.has(key))stores.set(key,new Store());return stores.get(key)};
const mock={name:'mock-blobs',setup(b){b.onResolve({filter:/^@netlify\/blobs$/},()=>({path:'mock',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:"export const getStore=o=>globalThis.getTestStore('prod:',o);export const getDeployStore=o=>globalThis.getTestStore('preview:',o)"}))}};
await build({entryPoints:['netlify/functions/_shared/requests.mts','netlify/functions/_shared/ai.mts','netlify/functions/_shared/project.mts','netlify/functions/photo-worker-background.mts','netlify/functions/eternion-mcp.mts'],outdir:'.test-build/requests',outbase:'netlify/functions',bundle:true,platform:'node',format:'esm',outExtension:{'.js':'.mjs'},plugins:[mock]});
const requests=await import('../../.test-build/requests/_shared/requests.mjs'),ai=await import('../../.test-build/requests/_shared/ai.mjs'),{initial}=await import('../../.test-build/requests/_shared/project.mjs'),{default:worker}=await import('../../.test-build/requests/photo-worker-background.mjs'),{default:mcp}=await import('../../.test-build/requests/eternion-mcp.mjs');let env;
beforeEach(()=>{stores.clear();env={CONTEXT:'production',URL:'https://site.example',DEPLOY_URL:'https://deploy.example',OPENAI_API_KEY:'test',ETERNION_BRIDGE_TOKEN:'test-token-32-characters-minimum-only'};globalThis.Netlify={env:{get:k=>env[k]}}});
const zone=(n=4)=>{const z=initial().zones['1'];z.scope='기둥 유지 LED 조명 교체';z.records=Array.from({length:n},(_,i)=>({kind:'before',url:'/uploads/photo-'+i+'.jpg',viewpoint:'위치 '+i}));return z};
test('all photos get individual durable requests; duplicate submissions do not create new jobs',async()=>{const z=zone();await Promise.all([requests.queueRequests('1',z,'eternion','owner'),requests.queueRequests('1',z,'eternion','owner')]);let rows=await requests.listRequests('1',z);assert.equal(rows.length,4);assert.equal(new Set(rows.map(r=>r.reference)).size,4);z.records.push({kind:'before',url:'/uploads/photo-new.jpg',viewpoint:'새 사진'});await requests.queueRequests('1',z,'eternion','owner');assert.equal((await requests.listRequests('1',z)).length,5);z.scope='새 계획';assert((await requests.listRequests('1',z)).every(r=>r.stale));await requests.queueRequests('1',z,'eternion','owner');assert.equal((await requests.listRequests('1',z)).filter(r=>!r.stale).length,5)});
test('manual claims are exclusive; wrong lease cannot write; result stays paired',async()=>{const z=zone(1);await requests.queueRequests('1',z,'eternion','owner');const row=(await requests.listRequests('1'))[0];const claims=await Promise.allSettled([requests.claimManual('1',row.id),requests.claimManual('1',row.id)]);assert.equal(claims.filter(r=>r.status==='fulfilled').length,1);const claimed=claims.find(r=>r.status==='fulfilled').value;await assert.rejects(requests.completeManual('1',row.id,'wrong','data:image/jpeg;base64,/9j/AA=='));await requests.completeManual('1',row.id,claimed.lease,'data:image/jpeg;base64,/9j/AA==');const done=(await requests.listRequests('1'))[0];assert.equal(done.status,'completed');assert.equal(done.image.reference,z.records[0].url);assert.equal(done.secretHash,undefined);await assert.rejects(requests.completeManual('1',row.id,claimed.lease,'data:image/jpeg;base64,/9j/AA=='))});
test('automatic jobs dispatch sequentially and duplicate worker delivery invokes provider only once',async()=>{const z=zone(2);await requests.queueRequests('1',z,'automatic','owner');for(let i=0;i<2;i++)await ai.fileStore().set('photo-'+i+'.jpg',new Uint8Array([255,216,255,0]).buffer,{metadata:{mime:'image/jpeg'}});const dispatched=[];let images=0;globalThis.fetch=async(url,o)=>{if(url.endsWith('-background')){dispatched.push(JSON.parse(o.body));return new Response(null,{status:202})}if(url.endsWith('/chat/completions'))return Response.json({choices:[{message:{content:JSON.stringify({summary:'관찰',photos:[],quotes:[],warnings:[]})}}]});images++;assert.equal(o.body.getAll('image[]').length,1);return Response.json({data:[{b64_json:'/9j/AA=='}]})};await requests.dispatchNext('1','https://site.example');await requests.dispatchNext('1','https://site.example');assert.equal(dispatched.length,1);const req=()=>new Request('https://site.example/worker',{method:'POST',body:JSON.stringify(dispatched[0])});await Promise.all([worker(req()),worker(req())]);assert.equal(images,1);assert.equal(dispatched.length,2);await worker(new Request('https://site.example/worker',{method:'POST',body:JSON.stringify(dispatched[1])}));assert.equal(images,2);assert((await requests.listRequests('1')).every(r=>r.status==='completed'));assert.notEqual((await requests.listRequests('1'))[0].image.url,(await requests.listRequests('1'))[1].image.url)});
test('failed dispatch can be retried without duplicating completed photos; stale retry blocked',async()=>{const z=zone(1);await requests.queueRequests('1',z,'automatic','owner');globalThis.fetch=async()=>{throw Error('offline')};await requests.dispatchNext('1','https://site.example');const r=(await requests.listRequests('1'))[0];assert.equal(r.status,'failed');z.scope='changed';await assert.rejects(requests.retryRequest('1',r.id,z),/변경/);z.scope=zone().scope;await requests.retryRequest('1',r.id,z);assert.equal((await requests.listRequests('1'))[0].status,'queued')});
test('connector denies missing credentials and foreign origin; authenticated protocol works',async()=>{const req=(body,auth=true,origin)=>new Request('https://site.example/eternion/mcp',{method:'POST',headers:{...(auth?{Authorization:'Bearer '+env.ETERNION_BRIDGE_TOKEN}:{}),...(origin?{Origin:origin}:{})},body:JSON.stringify(body)});assert.equal((await mcp(req({jsonrpc:'2.0',id:1,method:'tools/list'},false))).status,401);assert.equal((await mcp(req({jsonrpc:'2.0',id:1,method:'tools/list'},true,'https://evil.example'))).status,403);const r=await (await mcp(req({jsonrpc:'2.0',id:1,method:'initialize'}))).json();assert.equal(r.result.protocolVersion,'2025-03-26');assert.equal((await mcp(req({jsonrpc:'2.0',method:'notifications/initialized'}))).status,202);assert.equal((await (await mcp(req({jsonrpc:'2.0',id:2,method:'tools/list'}))).json()).result.tools.length,4)});
