import {createHash} from 'node:crypto';
import {aiStore,aiReady} from './ai.mjs';
import {Problem,type Zone} from './project.mjs';
export function imagePlan(zone:Zone){return createHash('sha256').update(JSON.stringify({scope:zone.scope,costs:zone.costs})).digest('hex')}
export function requestView(job:any,zone:Zone){if(!job)return null;const expired=['queued','running'].includes(job.status)&&Date.now()-Date.parse(job.created)>16*60000;return {id:job.id,key:job.requestKey,zone:job.zone,recipient:'에테르니언',source:job.snapshot.records[0],status:expired?'failed':job.status,error:expired?'생성 시간이 초과되었습니다. 다시 요청하세요.':job.error,created:job.created,finished:job.finished,image:job.image,result:job.result,stale:job.planFingerprint!==imagePlan(zone),instruction:job.instruction}}
export async function listImageRequests(id:string,zone:Zone){const store=aiStore(),index=await store.getWithMetadata('image-index-'+id,{type:'json'});const requests=await Promise.all((index?.data.keys||[]).map(async(key:string)=>requestView((await store.getWithMetadata(key,{type:'json'}))?.data,zone)));return requests.filter(Boolean)}
export async function createImageRequests(id:string,zone:Zone,actor:string,origin:string,urls?:unknown,process=true){
 if(urls!==undefined&&(!Array.isArray(urls)||urls.length>20||new Set(urls).size!==urls.length||urls.some(url=>typeof url!=='string'||!zone.records.some(r=>r.kind==='before'&&r.url===url))))throw new Problem('공사 전 사진을 최대 20장 선택하세요.');
 const photos=zone.records.filter(r=>r.kind==='before'&&(urls===undefined||(urls as string[]).includes(r.url)));if(!photos.length)throw new Problem('공사 전 사진을 먼저 등록하세요.');if(photos.length>20)throw new Problem('한 번에 최대 20장의 생성 요청이 가능합니다.');
 const store=aiStore(),keys:string[]=[];const plan=imagePlan(zone);
 for(const photo of photos){const key='image-'+createHash('sha256').update(id+'|'+photo.url+'|'+plan).digest('hex');keys.push(key);let previous=await store.getWithMetadata(key,{type:'json'});
 if(previous&&(['completed','queued','running'].includes(previous.data.status))&&!(previous.data.status!=='completed'&&Date.now()-Date.parse(previous.data.created)>16*60000))continue;
 const secret=crypto.randomUUID()+crypto.randomUUID(),snapshot=structuredClone(zone);snapshot.records=[photo];snapshot.quotes=[];
 const ready=process&&aiReady()&&!!zone.scope.trim();const job={id:crypto.randomUUID(),requestKey:key,zone:id,mode:'all',actor,recipient:'에테르니언',status:ready?'queued':'waiting',created:new Date().toISOString(),planFingerprint:plan,secretHash:createHash('sha256').update(secret).digest('hex'),snapshot,sources:[{url:photo.url,name:photo.viewpoint}],instruction:`에테르니언에게: ${id}층 / 촬영 위치 ${photo.viewpoint}. 첨부한 공사 전 사진 1장에 대응하는 공사 후 예상도 1장 생성. 같은 카메라 시점, 기둥·창·출입구 등 고정 구조 유지. 적용 공사: ${zone.scope||'공사 내용 입력 대기'}. 실제 준공 사진과 구분.`,error:ready?undefined:!process?'관리자 생성 실행 대기':!zone.scope.trim()?'공사 내용 입력 대기':'AI 연결 설정 대기'};
 const changed=await store.setJSON(key,job,previous?{onlyIfMatch:previous.etag}:{onlyIfNew:true});if(!changed.modified)continue;
 if(ready){try{const target=Netlify.env.get('DEPLOY_URL')||Netlify.env.get('URL')||origin;const response=await fetch(target+'/.netlify/functions/ai-worker-background',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({zone:id,id:job.id,requestKey:key,secret}),signal:AbortSignal.timeout(15000)});if(response.status!==202)throw Error('dispatch')}catch{const latest=await store.getWithMetadata(key,{type:'json'});if(latest?.data.id===job.id&&latest.data.status==='queued')await store.setJSON(key,{...job,status:'failed',error:'생성 요청을 전달하지 못했습니다. 다시 요청하세요.'},{onlyIfMatch:latest.etag})}}
 }
 const indexKey='image-index-'+id;let indexed=false;for(let retry=0;retry<5;retry++){const index=await store.getWithMetadata(indexKey,{type:'json'});const next=[...new Set([...(index?.data.keys||[]),...keys])];if(next.length>500)throw new Problem('층별 생성 요청 기록 한도에 도달했습니다. 관리자 정리가 필요합니다.');const result=await store.setJSON(indexKey,{keys:next},index?{onlyIfMatch:index.etag}:{onlyIfNew:true});if(result.modified){indexed=true;break}}if(!indexed)throw new Problem('요청 목록이 동시에 변경되었습니다. 다시 요청하면 중복 생성 없이 연결됩니다.',409);
 return listImageRequests(id,zone);
}
