import {Problem} from './project.mjs';
export function comparisonSchema(){const str={type:'string'},obj=(properties:any)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});return obj({summary:str,groups:{type:'array',items:obj({label:str,note:str,entries:{type:'array',items:obj({source:str,itemIndex:{type:'integer'}})}})},reviews:{type:'array',items:obj({source:str,scope:str,payment:str,warranty:str,schedule:str,exclusions:str,questions:{type:'array',items:str}})},warnings:{type:'array',items:str}})}
export function validateMapping(value:string,quotes:any[]){let v:any;try{v=JSON.parse(value)}catch{throw new Problem('견적 비교 결과 형식 오류',502)}if(!v||typeof v.summary!=='string'||v.summary.length>4000||!Array.isArray(v.groups)||v.groups.length>100||!Array.isArray(v.reviews)||v.reviews.length>6||!Array.isArray(v.warnings)||v.warnings.length>20)throw new Problem('견적 비교 형식 오류',502);const sources=new Map(quotes.map(q=>[q.source,q]));const used=new Set<string>();for(const group of v.groups){if(typeof group.label!=='string'||typeof group.note!=='string'||!Array.isArray(group.entries)||group.entries.length>100)throw new Problem('항목 대조 형식 오류',502);for(const e of group.entries){if(!sources.has(e.source)||!Number.isInteger(e.itemIndex)||e.itemIndex<0||e.itemIndex>=sources.get(e.source).items.length||used.has(e.source+':'+e.itemIndex))throw new Problem('원본 항목 참조 오류',502);used.add(e.source+':'+e.itemIndex)}}for(const r of v.reviews){if(!sources.has(r.source)||['scope','payment','warranty','schedule','exclusions'].some(k=>typeof r[k]!=='string')||!Array.isArray(r.questions)||r.questions.length>20||r.questions.some((q:any)=>typeof q!=='string'))throw new Problem('업체 검토 형식 오류',502)}if(v.warnings.some((x:any)=>typeof x!=='string'))throw new Problem('비교 확인 사항 형식 오류',502);return v}
export function compareQuotes(quotes:any[],mapping?:any){
 const unique=new Set(quotes.map(q=>q.source));if(unique.size!==quotes.length)throw new Problem('같은 견적서를 중복 인식했습니다. 원본을 확인하세요.',502);
 const groups=mapping?.groups?structuredClone(mapping.groups):[];const used=new Set(groups.flatMap((g:any)=>g.entries.map((e:any)=>e.source+':'+e.itemIndex)));
 // Every extracted item is retained, including rows omitted by AI matching.
 quotes.forEach(q=>q.items.forEach((r:any,i:number)=>{if(!used.has(q.source+':'+i)){const key=r.item.replace(/\s+/g,'').toLowerCase()+'|'+r.unit;let g=groups.find((g:any)=>g.exactKey===key);if(!g){g={label:r.item,note:'원문 품명·단위가 같은 항목만 자동 대조. 규격 확인 필요.',exactKey:key,entries:[]};groups.push(g)}g.entries.push({source:q.source,itemIndex:i})}}));
 const rows=groups.map((g:any)=>{const offers=quotes.map(q=>{const entries=g.entries.filter((e:any)=>e.source===q.source).map((e:any)=>q.items[e.itemIndex]);if(!entries.length)return {source:q.source,status:'견적에 미기재',item:null};if(entries.length>1)return {source:q.source,status:'다수 항목 · 직접 대조',item:null,items:entries};const r=entries[0];const arithmetic=r.qty!==null&&r.price!==null&&r.amount!==null&&Math.abs(Math.round(r.qty*r.price)-r.amount)>1;return {source:q.source,status:arithmetic?'수량×단가·금액 불일치':r.qty===null||r.price===null||r.amount===null?'인식값 확인 필요':'항목 확인 필요',item:r}});const complete=offers.every((o:any)=>o.item&&o.item.qty!==null&&o.item.price!==null&&o.item.amount!==null&&o.item.unit&&o.status!=='수량×단가·금액 불일치');const same=complete&&offers.every((o:any)=>o.item.unit===offers[0].item.unit&&o.item.qty===offers[0].item.qty);const amounts=offers.filter((o:any)=>o.item?.amount!==null&&o.item).map((o:any)=>o.item.amount);return {label:g.label,note:g.note,offers,comparable:same,spread:same&&amounts.length>1?Math.max(...amounts)-Math.min(...amounts):null,status:same?'수량·단위 동일 · 규격/포함 범위 확인 필요':'범위·수량·단위 또는 인식값 확인 필요'}});
 const known=quotes.filter(q=>Number.isSafeInteger(q.total));const totals=quotes.map(q=>({source:q.source,vendor:q.vendor,total:q.total,subtotal:q.subtotal,vat:q.vat,trade:q.trade||'미확인'}));
 return {summary:mapping?.summary||'원문 항목 기반 비교 초안',totals,totalSpread:known.length===quotes.length&&known.length>1?Math.max(...known.map(q=>q.total))-Math.min(...known.map(q=>q.total)):null,rows,reviews:mapping?.reviews||[],warnings:[...(mapping?.warnings||[]),'총액 차이는 표시된 금액 기준입니다. 공사 범위·규격·세금·제외 항목이 다르면 최저 금액만으로 업체를 결정할 수 없습니다.']};
}
